"""Added is_deleted

Revision ID: 243dfac9f661
Revises: 76f4d4b32bfd
Create Date: 2026-04-14 13:53:00.222525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243dfac9f661'
down_revision: Union[str, Sequence[str], None] = '76f4d4b32bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_deleted')
    # ### end Alembic commands ###
