"""add bandwidth to bucket

Revision ID: 76f4d4b32bfd
Revises: 45b7d0aa5826
Create Date: 2026-04-14 13:13:34.500825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f4d4b32bfd'
down_revision: Union[str, Sequence[str], None] = '45b7d0aa5826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('bandwidth_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'bandwidth_bytes')
    # ### end Alembic commands ###
