"""Added request counters

Revision ID: 9fcafe90676b
Revises: 243dfac9f661
Create Date: 2026-04-14 14:22:01.169902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcafe90676b'
down_revision: Union[str, Sequence[str], None] = '243dfac9f661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('count_read_requests', sa.Integer(),  server_default='0', nullable=False))
    op.add_column('buckets', sa.Column('count_write_requests', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'count_write_requests')
    op.drop_column('buckets', 'count_read_requests')
    # ### end Alembic commands ###
